### ISSUE TITLE
W-13465567: Missing policy documentation for `PolicyRef.name: route`

### ISSUE THREAD

**Issue by martinbjeldbak** [mulesoft/docs-gateway#193]
I'm wondering if the policy list at https://docs.mulesoft.com/policies/policies-included-directory is missing the `route` policy, or if you can help point me into the right direction of where I can find more about this policy.

For reference, it's used in (search `name: route`)
- https://docs.mulesoft.com/gateway/1.4/flex-local-configuration-reference-guide#policy-binding-examples
- https://help.mulesoft.com/s/article/How-to-add-a-URI-parameter-to-the-Flex-Gateway-service-address

If this is not the right place to post an issue, my apologies!

Thanks in advance

**Comment by chris-campbell9** [comment]
@martinbjeldbak, thanks for raising this issue. I've created an internal ticket to investigate. I'll update you when we are able to complete this work. Thanks again!

**Comment by chris-campbell9** [comment]
Hi @martinbjeldbak, we're going to add a note to the following section:
https://docs.mulesoft.com/gateway/1.5/flex-local-configuration-reference-guide#policy-binding-examples

The note will read:
"The `route` policy is required only when defining `PolicyBinding` entities in resource-based configurations. For instance, using `spec.services.routes` in an `ApiInstance` entity, either inline or as a resource, does not require defining the `route` policy."

I hope this clarifies when to use the policy. I'm not sure we need any further documentation, as this policy is only used in Local Mode, in resource-based `PolicyBinding` configurations.

The change with be published with our upcoming 1.6 release, in November.

**Comment by chris-campbell9** [comment]
Hi @martinbjeldbak, we'll be adding a page to the list of included policies, describing more about the route policy, including its parameters.

**Comment by martinbjeldbak** [comment]
Cheers @chris-campbell9 happy for you to close this issue

**Comment by chris-campbell9** [comment]
Hi @martinbjeldbak, I just merged a PR that adds new content describing the `route` policy. The new content will be published with our 1.6 release later this week. The new page will live in the Included Policies directory.

Here's a link to the PR:
https://github.com/mulesoft/docs-gateway/pull/437

I'll go ahead and close this issue.

Thanks again for letting us know about this!

**Comment by martinbjeldbak** [comment]
Awesome, thank you @chris-campbell9 !
